### ISSUE TITLE
Demo recording bug to be fixed.

### ISSUE THREAD

**Issue by ghost** [JadingTsunami/prboomX#1]
https://github.com/coelckers/prboom-plus/issues/522

This demo recording bug has become a problem for me as well in PrBoom+.

Since I love PrBoom+ so much, I can't leave it, but since PrBoom+ is no longer in development, so it would be really good if you fix this bug.

**Comment by JadingTsunami** [comment]
Can you explain what bad thing is happening that you would like to see fixed? What should happen instead?

**Comment by JadingTsunami** [comment]
Looks like the users deleted their account. I think they want the extended header removed, which is what the other ports (dsda, woof) seem to have done. So I'll do that too and close this with that change. I'll leave the reading code intact so, if present, demos will still play back as normal.
