### ISSUE TITLE
[Feature Request] Disable "Gave Saved" messages when quicksaving without disabling messages altogether

### ISSUE THREAD

**Issue by KronaDComics** [JadingTsunami/prboomX#10]
First of all I'd like to say this is the best source port and the official continuation of PrBoomPlus in my book, thank you for this.

An option to disable  "Gave Saved" messages when quicksaving without disabling messages altogether and perhaps even the sound would be much appreciated, as I tend to play strange couple of wads that require experimenting and this can be quite annoying.

**Comment by JadingTsunami** [comment]
Sure. Is this also desirable for loading and quickloading?

**Comment by KronaDComics** [comment]
I'm not aware of any message that shows when you're loading or quickloading except the screen melt effect, which is understandable

**Comment by JadingTsunami** [comment]
Added in https://github.com/JadingTsunami/prboomX/commit/e2919dc8d59ada44aa26c541f4db92e14b185094

Menu option to not have a save message. The sound still plays as this could affect demo compatibility.
