### ISSUE TITLE
Doom II : Map 21 Nirvana texture issue on hardware renderer OpenGL

### ISSUE THREAD

**Issue by KronaDComics** [JadingTsunami/prboomX#11]
*Using the latest development build Commit [87cb8ff] (https://github.com/JadingTsunami/prboomX/actions/runs/8724178088)

*Issue doesn't appear on Software Renderer. 

*GPU is Ryzen 3 3250U Integrated 

*IWAD : Doom II v1.9

Demonstration of glitch using with the correct timestamp: https://youtu.be/cmmvEOd19Ok?t=4351

**Comment by JadingTsunami** [comment]
Ah, yeah, that's a bug in the map itself. GZDoom actually patches the map when it's loaded if I recall correctly.

The same glitch happens in dsda and other similar ports.

I suppose a patching option is possible but will be very map-specific.

**Comment by KronaDComics** [comment]
Ah I see. I suppose this can be closed as the map itself is bugged.

**Comment by JadingTsunami** [comment]
I'll think on it a bit. There are other famously-bugged IWAD maps, like E3M9. So maybe a map-specific patching is something to consider.

At any rate thanks for the report.

**Comment by JadingTsunami** [comment]
I looked into this one, and it doesn't seem like there's a reasonable path to fix this without affecting important things like demo compatibility. So I will close it for now but if somehow there's a path I will reopen it at that point.
