### ISSUE TITLE
[Feature Request] Disable View-Bobbing Option

### ISSUE THREAD

**Issue by KronaDComics** [JadingTsunami/prboomX#13]
View-Bobbing disable option similar to other source ports without disabling weapon bob

**Comment by JadingTsunami** [comment]
Added `weapon_bob_only` cvar to enable weapon-only bobbing option.

**Comment by KronaDComics** [comment]
Unfortunately this problem seems to be introduced where it doesn't bob during the death animation https://files.catbox.moe/fo320c.mp4

**Comment by JadingTsunami** [comment]
> Unfortunately this problem seems to be introduced where it doesn't bob during the death animation https://files.catbox.moe/fo320c.mp4

Thanks for the report; should be fixed in the latest build.
