### ISSUE TITLE
Mac version requires big sur

### ISSUE THREAD

**Issue by dfgdgdgfd** [JadingTsunami/prboomX#2]
I imagine this is an oversight on your part and you developed it on big sur - I don't think many people would be running this.

**Comment by JadingTsunami** [comment]
Could you try [this](https://github.com/JadingTsunami/prboomX/suites/16096974318/artifacts/918968493) artifact build? It should be enabled for versions newer than Big Sur.

**Comment by dfgdgdgfd** [comment]
> Could you try [this](https://github.com/JadingTsunami/prboomX/suites/16096974318/artifacts/918968493) artifact build? It should be enabled for versions newer than Big Sur.

I only have high sierra.  Even the latest gzdoom will run on sierra.

**Comment by JadingTsunami** [comment]
> > Could you try [this](https://github.com/JadingTsunami/prboomX/suites/16096974318/artifacts/918968493) artifact build? It should be enabled for versions newer than Big Sur.
> 
> I only have high sierra. Even the latest gzdoom will run on sierra.

In that case, you will have to build from source unfortunately. I am not able to provide a pre-made binary for you.

**Comment by dfgdgdgfd** [comment]
Ok, I understand that high sierra is quite old now - it's just that usually people never set the required minimum version of os x for source ports, or set them to tiger (In the case of prboom+).  I'd like to try the linux ports, but I'd need to compile them, wouldn't I?

**Comment by JadingTsunami** [comment]
> Ok, I understand that high sierra is quite old now - it's just that usually people never set the required minimum version of os x for source ports, or set them to tiger (In the case of prboom+). I'd like to try the linux ports, but I'd need to compile them, wouldn't I?

There are linux builds available too; you can see if they are suitable for you. They're available in the release section, or you could pull from [the latest artifacts](https://github.com/JadingTsunami/prboomX/actions/runs/6164785610) (scroll down to find them).

**Comment by dfgdgdgfd** [comment]
I tried to run them on lubuntu but was just asked what I wanted to use to open the file with.

**Comment by JadingTsunami** [comment]
> I tried to run them on lubuntu but was just asked what I wanted to use to open the file with.

You might need to enable the execute flag on the binary file first.

On the macOS side - I am not (at least to my knowledge) setting the minimum version; it's just the only build system I have available for these builds that ends up requiring at least that version. If you know of some way to work around that limitation, I could try to enable it, but I'm not aware of any such thing.

**Comment by dfgdgdgfd** [comment]
Execute is set to anybody for all files, but still have the same problem.  Seems to think it's a shared library file.

**Comment by JadingTsunami** [comment]
> Execute is set to anybody for all files, but still have the same problem. Seems to think it's a shared library file.

Permissions yes, but did you set the execute flag on the binary file itself? The linux build was done on ubuntu so I would imagine lubuntu should work as well.

**Comment by dfgdgdgfd** [comment]
The binary file is just the file "prboomx" isn't it? [https://ibb.co/0YV1GhN](url)

**Comment by JadingTsunami** [comment]
> The binary file is just the file "prboomx" isn't it? [https://ibb.co/0YV1GhN](url)

Yes, that's it. But the file manager is not exposing the "execute" flag to you (normally it shows as a check box there). Are you perhaps running a 32-bit only OS? The linux builds are for 64-bit.

**Comment by dfgdgdgfd** [comment]
That would be the issue.  I don't have much of a use for the 64 bit version as I have windows on all my 64 bit pc's.  But I'll keep it in mind.

**Comment by JadingTsunami** [comment]
> That would be the issue. I don't have much of a use for the 64 bit version as I have windows on all my 64 bit pc's. But I'll keep it in mind.

OK - yes, right now the builds are 64-bit. But you can easily build from source for a 32-bit OS.

**Comment by dfgdgdgfd** [comment]
I've been waiting a long time now for a version of prboom (For my daily driver, so the windows builds are fine) with a resurrect command, so thanks for that.  Any chance of being able to bind keys to console commands in future?

**Comment by JadingTsunami** [comment]
> I've been waiting a long time now for a version of prboom (For my daily driver, so the windows builds are fine) with a resurrect command, so thanks for that. Any chance of being able to bind keys to console commands in future?

Yep, that's on the list. I have some other stuff I want to get to first though.

**Comment by JadingTsunami** [comment]
Unless there's any objection, I will close this one as I'm providing all the builds that I'm able to provide at this time. For anything not covered, building from source is the available option (and should be supported by the cmake system that's provided with the source code, so should be ready-to-go).
